#source 'https://rubygems.org'
source 'http://ruby.taobao.org'

gem 'jekyll'
# gem 'jekyll-assets'
# gem 'maruku'
gem 'rake'
# gem 'sass'
gem 'uglifier'
gem 'github-pages'
gem 'rack-jekyll'
gem 'unicorn'
