source 'https://rubygems.org'
#source 'http://ruby.taobao.org'
# source 'https://mirrors.tuna.tsinghua.edu.cn/rubygems/'

gem 'jekyll'
# gem 'jekyll-assets'
# gem 'maruku'
gem 'rake'
# gem 'sass'
gem 'uglifier'
gem 'pygments.rb'
gem 'github-pages'
gem 'rack-jekyll'
gem 'rack-contrib', :require => 'rack/contrib/try_static'
gem 'unicorn'
gem 'directory_watcher'
